# -*- coding: utf-8 -*-
"""
Created on Fri Sep 13 16:50:46 2019

@author: DW24
"""

# Project Euler - Problem 12

#The sequence of triangle numbers is generated by adding the natural numbers.
#So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
#The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#36: 1,2,3,4,6,9,12,18,36
#55: 1,5,11,55
#We can see that 28 is the first triangle number to have over five divisors.
#
#What is the value of the first triangle number to have over
#five hundred divisors?
#

# play around with triangle number generator

import numpy as np

array = np.arange(1, 500 + 1)

# 500th triangle number
p = sum(array)

for i in 1:500:
    
    n = 1
    

