---
title: "ex19"
author: "Dan Wakeling"
date: "05/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
options(scipen = 999)

```

## Factorial digit sum

n! means n × (n − 1) × ... × 3 × 2 × 1

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

Find the sum of the digits in the number 100!

## Notes

Factors of 10 can be removed
Factors of 5 can be removed when combined with a factor of 2

```{r code one}

# already removed a 2 and 5
df <- data.frame(
  vals = c(1:100)
) %>% 
  mutate(div_ten = vals %% 10,
         div_five = vals %% 5,
         div_two_lag = lead(vals, 1) %% 5,
         
         vals_new = case_when(
           div_ten == 0 ~ as.integer(vals / 10),
           # div_five == 0 & div_ten != 0 ~ as.integer(vals / 5),
           # div_two_lag == 0 & lead(div_ten, 1) != 0 ~ as.integer(vals / 2),
           TRUE ~ vals))
# %>% 
#   filter(!vals %in% c(2, 20, 25, 50, 100))

result <- cumprod(df$vals_new)

n <- result[length(result)]

string <- as.character(n) %>% 
  str_split(pattern = "") %>% 
  unlist()

df_final <- data.frame(
  vals = string
) %>% 
  mutate(string = as.integer(string),
         string = cumsum(string))

final_result <- max(df_final$string)

```

